name: CI

on:
  push:
  pull_request:

env:
  CARGO_INCREMENTAL: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [beta, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo check

  clippy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy -- -Dclippy::all -Dclippy::pedantic

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Create config values
        id: config_values
        run: |
          REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "::set-output name=CRATE_NAME::${REPOSITORY_NAME//-/_}"
      - run: cargo doc --document-private-items --no-deps
      - name: Add redirect page
        run: echo '<meta http-equiv="refresh" content="0;URL=./${{ steps.config_values.outputs.CRATE_NAME }}/">' > ./target/doc/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
